services:
  db:
    image: postgres:16
    container_name: invoice_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: R4ph43lLim429
      POSTGRES_DB: invoice_manager
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d invoice_manager"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: